/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.115
 * Generated at: 2026-03-26 06:56:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1774507237589L));
    _jspx_dependants.put("jar:file:/C:/Users/楊子毅/Desktop/巨匠專門/社團影片/社團範例/測驗測試/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OnlineExam/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425949870000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
String msg = request.getParameter("msg");
pageContext.setAttribute("msg", msg);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>在线考试————登录</title>\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link href=\"");
      out.print(basePath );
      out.write("bootstrap-3.3.5-dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"//cdn.bootcss.com/respond.js/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("    <script src=\"");
      out.print(basePath );
      out.write("bootstrap-3.3.5-dist/js/jquery-1.11.3.min.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("bootstrap-3.3.5-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"");
      out.print(basePath );
      out.write("proJs/login.js?v=0.55\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html,body {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".box {\r\n");
      out.write("	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#003700', endColorstr='#003700'); /*  IE */\r\n");
      out.write("	background-image:linear-gradient(bottom, #003700 0%, #003700 100%);\r\n");
      out.write("	background-image:-o-linear-gradient(bottom, #003700 0%, #003700 100%);\r\n");
      out.write("	background-image:-moz-linear-gradient(bottom, #003700 0%, #003700 100%);\r\n");
      out.write("	background-image:-webkit-linear-gradient(bottom, #003700 0%, #003700 100%);\r\n");
      out.write("	background-image:-ms-linear-gradient(bottom, #003700 0%, #003700 100%);\r\n");
      out.write("	\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".login-box {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width:500px;\r\n");
      out.write("	height: 400px;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("\r\n");
      out.write("	margin-top: -200px;\r\n");
      out.write("	/*设置负值，为要定位子盒子的一半高度*/\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width:500px){\r\n");
      out.write("	.login-box {\r\n");
      out.write("		left: 50%;\r\n");
      out.write("		/*设置负值，为要定位子盒子的一半宽度*/\r\n");
      out.write("		margin-left: -250px;\r\n");
      out.write("	}\r\n");
      out.write("}	\r\n");
      out.write("\r\n");
      out.write(".form {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width:500px;\r\n");
      out.write("	height: 275px;\r\n");
      out.write("	margin: 25px auto 0px auto;\r\n");
      out.write("	padding-top: 25px;\r\n");
      out.write("}	\r\n");
      out.write(".login-content {\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	max-width:500px;\r\n");
      out.write("	background-color: rgba(255, 250, 250, .6);\r\n");
      out.write("	float: left;\r\n");
      out.write("}		\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write(".input-group {\r\n");
      out.write("	margin: 0px 0px 30px 0px !important;\r\n");
      out.write("}\r\n");
      out.write(".form-control,\r\n");
      out.write(".input-group {\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group {\r\n");
      out.write("	margin-bottom: 0px !important;\r\n");
      out.write("}\r\n");
      out.write(".login-title {\r\n");
      out.write("	padding: 20px 10px;\r\n");
      out.write("	background-color: rgba(0, 128, 0, .6);\r\n");
      out.write("}\r\n");
      out.write(".login-title h1 {\r\n");
      out.write("	margin-top: 10px !important;\r\n");
      out.write("}\r\n");
      out.write(".login-title small {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link p {\r\n");
      out.write("	line-height: 20px;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write(".btn-sm {\r\n");
      out.write("	padding: 8px 24px !important;\r\n");
      out.write("	font-size: 16px !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body >\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("		<div class=\"login-box\">\r\n");
      out.write("			<div class=\"login-title text-center\">\r\n");
      out.write("				<h1><small>铭成在线考试系统</small></h1>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"login-content \">\r\n");
      out.write("			<div class=\"form\">\r\n");
      out.write("			<form id=\"loginform\" action=\"");
      out.print(basePath );
      out.write("syslogin\" method=\"post\">\r\n");
      out.write("			\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></span>\r\n");
      out.write("							<input type=\"text\" name=\"USERNAME\" class=\"form-control\" placeholder=\"用户名\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				");
//提示用户名密码错误 
      out.write("\r\n");
      out.write("				");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /login.jsp(133,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty msg }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					<script type=\"text/javascript\">\r\n");
            out.write("						var msg=");
            out.print(msg);
            out.write(";\r\n");
            out.write("						if(msg==1){\r\n");
            out.write("							alert ('用户名密码错误！');\r\n");
            out.write("						}else if(msg==2){\r\n");
            out.write("							$(function(){\r\n");
            out.write("								alert ('注册失败！');\r\n");
            out.write("								register();	//打开注册窗口\r\n");
            out.write("							});\r\n");
            out.write("						}else if(msg==3){\r\n");
            out.write("							alert ('该用户已经存在！');\r\n");
            out.write("							$(function(){\r\n");
            out.write("								register();	//打开注册窗口\r\n");
            out.write("							});\r\n");
            out.write("						}\r\n");
            out.write("					</script>\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } finally {
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      }
      out.write("\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></span>\r\n");
      out.write("							<input type=\"password\" name=\"PASSWORD\" class=\"form-control\" placeholder=\"密码\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group form-actions\">\r\n");
      out.write("					<div class=\"col-xs-4 col-xs-offset-4 \">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-sm btn-info\" ><span class=\"glyphicon glyphicon-off\"></span> 登录</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-6 link\">\r\n");
      out.write("						<p class=\"text-center remove-margin\"><small>忘记密码？</small> \r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-xs-6 link\">\r\n");
      out.write("						<p class=\"text-center remove-margin\"><small>还没注册?</small> <a href=\"javascript:void(0)\" onclick=\"register ()\" id=\"link_reg\"><small>注册</small></a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function register (){\r\n");
      out.write("	$(\"#registerModal\").css({'margin-top':function (){return '300';}}).modal();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"registerModal\">\r\n");
      out.write("	<div class=\"modal-dialog\">\r\n");
      out.write("		<div class=\"modal-content\">\r\n");
      out.write("			<div class=\"modal-header\">\r\n");
      out.write("				<button class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("					<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("					<span class=\"sr-only\">Close</span>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-body\" >\r\n");
      out.write("			<form id=\"registerform\" action=\"");
      out.print(basePath );
      out.write("sysregister\" method=\"post\">\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-user\"></span></span>\r\n");
      out.write("							<input type=\"text\" name=\"USERNAME\" id=\"username\" class=\"form-control\" placeholder=\"用户名\" maxlength=\"20\" onfocus=\"$('#usernameInfo').show()\" onblur=\"$('#usernameInfo').hide()\" />\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"well\" id=\"usernameInfo\" style=\"display: none;\">\r\n");
      out.write("						提示:用户名长度为6-20位英文或数字！\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></span>\r\n");
      out.write("							<input type=\"password\" name=\"PASSWORD\" id=\"password\" class=\"form-control\" placeholder=\"密码\" maxlength=\"20\" onfocus=\"$('#passwordInfo').show()\" onblur=\"$('#passwordInfo').hide()\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"well\" id=\"passwordInfo\" style=\"display: none;\">\r\n");
      out.write("						提示:密码长度为6-20位英文或数字！\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-lock\"></span></span>\r\n");
      out.write("							<input type=\"password\" name=\"REPASSWORD\" id=\"repassword\" class=\"form-control\" placeholder=\"重复密码\" maxlength=\"20\" onfocus=\"$('#repasswordInfo').show()\" onblur=\"$('#repasswordInfo').hide()\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"well\" id=\"repasswordInfo\" style=\"display: none;\">\r\n");
      out.write("						提示:要与上面输入的密码一致哦！\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-tower\"></span></span>\r\n");
      out.write("							<input type=\"text\" name=\"NAME\" id=\"wxname\" class=\"form-control\" placeholder=\"fullname\" maxlength=\"20\" onfocus=\"$('#wxnameInfo').show()\" onblur=\"$('#wxnameInfo').hide()\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"well\" id=\"wxnameInfo\" style=\"display: none;\">\r\n");
      out.write("						提示:真实姓名哦！\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-group\">\r\n");
      out.write("					<div class=\"col-xs-12  \">\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-send\"></span></span>\r\n");
      out.write("							<input type=\"text\" name=\"EMAIL\" id=\"email\" class=\"form-control\" placeholder=\"邮箱\" maxlength=\"100\" onfocus=\"$('#emailInfo').show()\" onblur=\"$('#emailInfo').hide()\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"well\" id=\"emailInfo\" style=\"display: none;\">\r\n");
      out.write("						提示:xxxxx@xx.com,这是找回密码的重要凭证！\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"form-group form-actions\">\r\n");
      out.write("					<div class=\"col-xs-4 col-xs-offset-4 \">\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-sm btn-info\" onclick=\"subRegister()\"><span class=\"glyphicon glyphicon-off\"></span> 注册</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"modal-footer\">\r\n");
      out.write("				<button class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
